typography_spectrum: 0.34928
color:
  brandColors:
    - '#a8a7a5'
    - '#8e8d8b'
    - '#c3c2c0'
    - '#5e5d5b'
    - '#f2f0f1'
  brandStrength: 0.125
  lightness: 0.125
  saturation: 0.9375
  rhythmicContrast: 0.75
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.67419
analytics:
  google: null
  facebook: null
  twitter: null
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/f5d6be48-c8ec-4621-bc2e-b5bdbb321fdf.png
name: esecolectivo
cta:
  domain: null
  bucket: null
  version: null
favicon: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: ESE colectivo
purpose: []
