name: esecolectivo
favicon: null
layout_spectrum: 0.74458
typography_spectrum: 0.34928
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#a8a7a5'
    - '#8e8d8b'
    - '#c3c2c0'
    - '#5e5d5b'
    - '#f2f0f1'
  brandStrength: 0.125
  lightness: 0.125
  saturation: 0.4375
  rhythmicContrast: 0.75
purpose: []
